name: Build OPK
 
on:
  workflow_dispatch:
  push:
    branches: [ opendingux ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
 
    - name: Build the OPK
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build --progress=plain -t my-opk-image .
    - name: Extract OPK
      run: |
        docker run --rm my-opk-image > my-opk-package.ipk
    - name: Upload OPK
      uses: actions/upload-artifact@v2
      with:
        name: my-opk-package
        path: my-opk-package.ipk
